name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        configuration:
          - Debug
          - Release
    name: Build and Run ${{ matrix.configuration }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: actions/setup-dotnet@v3.2.0
        with:
          global-json-file: ./global.json
          cache: true

      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6

      - name: Run with ${{ matrix.configuration }}
        shell: pwsh
        run:  dotnet run --project .\Dotnet\ --configuration ${{ matrix.configuration }}